[package]
name = "orogene"
version = "0.1.0"
authors = ["Kat Marchán <kzm@zkat.tech>"]
edition = "2018"
description = "wip"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
surf = { git = "git://github.com/http-rs/surf.git" }
async-tar = "0.1.1"
async-std = { version = "1.6.2", features = ["attributes", "unstable"] }
clap = { git = "https://github.com/clap-rs/clap" }
anyhow = "1.0.31"
smol = "0.1.18"
async-compression = { version = "0.3.5", features = ["gzip", "futures-io"] }
http-types = "2.3.0"
cacache = "7.0.0"
futures = "0.3.5"
tar = "0.4.29"
flate2 = "1.0.16"
memmap = "0.7.0"

[[bin]]
name = "oro"
path = "src/main.rs"
