[package]
name = "orogene"
version = "0.1.0"
authors = ["Kat Marchán <kzm@zkat.tech>"]
edition = "2018"
description = "wip"
license = "MIT"
build = "build.rs"

[workspace]
members = ["crates/*"]

[dependencies]
rogga = { path = "./crates/rogga" }

surf = { git = "git://github.com/http-rs/surf.git", default-features = false, features = ["h1-client"]}
async-tar = "0.1.1"
async-std = { version = "1.6.2", features = ["attributes", "unstable"] }
clap = { git = "https://github.com/clap-rs/clap" }
anyhow = "1.0.31"
smol = "0.1.18"
async-compression = { version = "0.3.5", features = ["gzip", "futures-io"] }
http-types = "2.3.0"
cacache = "8.0.0"
futures = "0.3.5"
bincode = "1.3.1"
pin-project-lite = "0.1.7"
ssri = "5.0.0"

[build-dependencies]
embed-resource = "1.3.3"

[[bin]]
name = "oro"
path = "src/main.rs"
