[package]
name = "oro-command"
version = "0.1.0"
authors = ["Kat Marchán <kzm@zkat.tech>"]
edition = "2018"

[dependencies]
anyhow = "1.0.24"
clap = { git = "https://github.com/clap-rs/clap" }
oro-config = { path = "../oro-config" }
async-trait = "0.1.19"
