[package]
name = "rogga"
version = "0.1.0"
authors = ["Kat Marchán <kzm@zkat.tech>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-tar = "0.1.1"
async-std = { version = "1.6.2", features = ["attributes", "unstable"] }
async-compression = { version = "0.3.5", features = ["gzip", "futures-io"] }
bincode = "1.3.1"
cacache = "8.0.0"
futures = "0.3.5"
ssri = "5.0.0"
thiserror = "1.0.20"
