[package]
name = "oro-client"
version = "0.1.0"
authors = ["Kat Marchán <kzm@zkat.tech>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
surf = { git = "git://github.com/http-rs/surf.git", default-features = false, features = ["h1-client"]}
thiserror = "1.0.20"
